[package]
name = "asn1-lsp"
version = "0.1.0"
edition = "2024"

[dependencies]
tower-lsp = "0.20.0"
tree-sitter = "0.25.10"
tree-sitter-asn1 = { git = "https://github.com/tdanner/tree-sitter-asn1" }
tokio = { version = "1.37.0", features = ["rt-multi-thread", "macros", "io-std"] }
